baseURL = 'https://www.pingfan.me/blog/'
languageCode = 'en-us'
title = 'Pingfan'
theme = "hugo-paper"
[taxonomies]
  tag = "tags"
  category = "categories"


[menu]
[[menu.main]]
  identifier = 'about'
  name = 'about hugo'
  pre = "<i class='fa fa-heart'></i>"
  url = '/Pingfan/Pingfan'
  weight = -110
[[menu.main]]
  name = '英语'
  post = "<span class='alert'>IELTS!</span>"
  pre = "<i class='fa fa-road'></i>"
  url = 'posts/ielts/'
  weight = -100

[[menu.main]]
  name = '计算机'
  post = "<span class='alert'>IELTS!</span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/about/'
  weight = -100

[[menu.main]]
  name = '日记'
  post = "<span class='alert'>IELTS!</span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/diary/'
  weight = -100