baseURL = 'https://pingfan.me/blog/'
languageCode = 'en-us'
title = 'Pingfan'
theme = "hugo-paper"
[taxonomies]
  tag = "tags"
  category = "categories"


[menu]
[[menu.main]]
  identifier = 'about me'
  name = 'about'
  pre = "<i class='fa fa-heart'></i>"
  url = '/Pingfan/Pingfan'
  weight = -110
